services:
  dhcp:
    build:
      context: ./ztp_server/
      dockerfile: Dockerfile.ztp
    container_name: service_dhcp
    network_mode: host
    # ports:
    #   - 67:67/udp
    environment:
      - BACKEND_URL=http://127.0.0.1:8080
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.backend 
    container_name: fastapi-web-ztp
    ports:
      - 8080:8080
