volumes:
  static:

services:
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
  web:
    build: app
    depends_on:
      - db
    restart: always
    volumes:
      - ./app/media:/app/media
      - static:/app/staticfiles
    environment:
      HOSTNAME: ${HOSTNAME}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}

      IS_PRODUCTION: ${IS_PRODUCTION}
    command: /bin/bash entrypoint.sh
    develop:
      watch: 
        - action: sync+restart
          path: ./app
          target: /app
        - action: rebuild
          path: ./app/requirements.txt
  caddy:
    build: caddy
    restart: always
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - ./app/media:/web/media
      - static:/web/staticfiles
    environment:
      HTTP_URL: http://${HOSTNAME}:${HTTP_PORT}
      HTTPS_URL: https://${HOSTNAME}:${HTTPS_PORT}
    depends_on:
      - web
    command: |
      sh -c "envsubst < Caddyfile.tmpl > Caddyfile && \
      caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOSTNAME}:${HTTP_PORT}/status/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
