version: '3.8'

services:
  caddy:
    container_name: caddy
    image: caddy:2
    networks:
      - web
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django-docker_media:/django-docker/media  # Volume partagé avec Django
      - django-docker_static:/django-docker/staticfiles  # Volume partagé avec Django
    working_dir: /srv

  db:
    container_name: postgres
    image: postgres:15
    networks:
      - web
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=webztp_db
      - POSTGRES_USER=webztp_user
      - POSTGRES_PASSWORD=webztp_password
    ports:
      - "5432:5432"

  web:
    container_name: web
    hostname: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - web
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://webztp_user:webztp_password@db:5432/webztp_db
    depends_on:
      - db

  dhcp:
    container_name: dhcp
    hostname: dhcp
    build:
      context: "."
      dockerfile: Dockerfile.dhcp
    restart: unless-stopped
    privileged: true  # Nécessaire pour sudo et les opérations DHCP
    volumes:
      - ".:/app"
    environment:
      - DATABASE_URL=postgresql://webztp_user:webztp_password@db:5432/webztp_db
    depends_on:
      - db

volumes:
  caddy_data: 
  caddy_config:
  django-docker_media:
  django-docker_static:
  postgres_data:

networks:
  web:
    driver: bridge
