version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1

  dhcp:
    build:
      context: ./dhcp
      dockerfile: Dockerfile.dhcp   # Vous pouvez créer un Dockerfile spécifique pour le serveur DHCP
    container_name: dhcp_server
    network_mode: host
    environment:
      - BACKEND_URL=http://127.0.0.1:8000
