services: 
  fastapi:
    build: 
      context : .
    container_name: fastapi-web-ztp
    ports:
      - 8080:8080
    develop: 
      watch: 
      - path: .
        action: sync+restart
        target: . 
