[tool.black]
line-length = 88  # You can adjust this
target-version = ['py311']  # Adjusted for Python 3.11
skip-string-normalization = false
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''
