site_name: Web-ZTP
site_description: Solution simple pour la configuration Zero Touch Provisioning (ZTP) des équipements réseau Cisco
site_author: Web-ZTP Team
site_url: https://github.com/Chadi-Mangle/web-ztp

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: Chadi-Mangle/web-ztp
repo_url: https://github.com/Chadi-Mangle/web-ztp

nav:
  - Accueil: index.md
  - Fonctionnalités: features.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Utilisation: utilisation.md
  - Structure du projet: structure.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde 